name: Relog
main: pawarenessc\RL\Main
version: 1.0.0
api:
- 4.0.0
- 4.0.0-BETA1
- 5.0.0
- 5.0.0-ALPHA1
author:
- PawarenessC
- roi611 #add support for PMMP5
load: POSTWORLD
description: Relog...
commands:
 relog:
  description: "リログできます"
  usage: "/relog"
  permission: pocketmine.group.user
 setip:
  description: "この鯖のipとportを設定"
  usage: "/setip"
  permission: "relog.command"

permissions:
  relog.command:
    default: op